baseURL = "https://matris.in/"
languageCode = "en-us"
title = "MATRIS - Embrace Your Inner Devi"
theme = ""

[params]
  description = "Premium handloom sarees celebrating the divine feminine"
  author = "MATRIS"
  
  # Brand Colors (Locked)
  colorVermillion = "#E34234"
  colorTeal = "#0D4C4A"
  colorCream = "#F5F1E8"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Collections"
    url = "/collections/"
    weight = 1
  [[menu.main]]
    name = "Philosophy"
    url = "/philosophy/"
    weight = 2
  [[menu.main]]
    name = "Lookbook"
    url = "/lookbook/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
